### ISSUE TITLE
Magic Bursted enfleebles not being captured by the Target Bar

### ISSUE THREAD

**Issue by zXzLenin** [tirem/HXUI#20]
Title lol 
![horizon-loader (2023-01-22) (15-06-58)](https://user-images.githubusercontent.com/118400371/213938232-106491ac-e16a-49ce-ba61-ae8b8a6e7578.jpg)

**Comment by Marandopsu** [comment]
Will just comment instead of making a new issue: Bio 2 isnt tracked either (not just MB'd, ever). Bio1 is fine

**Comment by tirem** [comment]
This should have been addressed in the most recent version :) capturing all debuffs is an ongoing process so if you notice any in the most recent release definitely post an issue again! TY!
