### ISSUE TITLE
Opacity/Background color options

### ISSUE THREAD

**Issue by demesm** [tirem/HXUI#9]
Would be awesome if we had a slider for each ui element that could control opacity, and the option to choose the colors

**Comment by darkedone02** [comment]
I needed this as well.

**Comment by AzrielltheWise** [comment]
I know a lot of people want this.  Atom0s is working on a plugin/addon to hide parts of the vanilla FFXI UI, which would be great for people who want to put Party List on top of the vanilla party list while maintaining the transparent background.

Personally, I edited the asset for Party List to make it match my chat box.  Options are always good though :)

**Comment by tirem** [comment]
The party background now has an opacity slider and the ability to chose which image from a folder to use :)
